# These are supported funding model platforms

github: mantisfury  # Replace with your GitHub username for GitHub Sponsors
ko_fi: # Add your Ko-fi username here after creating account (e.g., arkham_mirror)
# open_collective: # Add your Open Collective name here if you set it up later

# You can add custom URLs too:
# custom: ['https://www.paypal.me/YOUR_USERNAME', 'https://buymeacoffee.com/YOUR_USERNAME']
