# These are supported funding model platforms

github: mantisfury  # GitHub Sponsors (0% fees!)
ko_fi: arkhammirror  # Ko-fi for one-time donations
# open_collective: # Add your Open Collective name here if you set it up later

# You can add custom URLs too:
# custom: ['https://www.paypal.me/YOUR_USERNAME', 'https://buymeacoffee.com/YOUR_USERNAME']
