"""Data models for the Provenance Shard."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class ChainStatus(Enum):
    """Status of an evidence chain."""
    DRAFT = "draft"
    ACTIVE = "active"
    VERIFIED = "verified"
    COMPLETED = "completed"
    ARCHIVED = "archived"


class LinkType(Enum):
    """Type of relationship between artifacts."""
    DERIVED_FROM = "derived_from"          # Target derived from source
    TRANSFORMED_TO = "transformed_to"      # Source transformed to target
    EXTRACTED_FROM = "extracted_from"      # Target extracted from source
    GENERATED_BY = "generated_by"          # Target generated by source process
    USED_BY = "used_by"                    # Source used by target process
    SUPPORTS = "supports"                  # Source supports target claim
    CONTRADICTS = "contradicts"            # Source contradicts target claim
    RELATED_TO = "related_to"              # Generic relationship
    VERSION_OF = "version_of"              # Target is version of source
    COPY_OF = "copy_of"                    # Target is copy of source


class ArtifactType(Enum):
    """Type of tracked artifact."""
    DOCUMENT = "document"
    ENTITY = "entity"
    CLAIM = "claim"
    EVIDENCE = "evidence"
    HYPOTHESIS = "hypothesis"
    MATRIX = "matrix"
    REPORT = "report"
    EMBEDDING = "embedding"
    EXTRACTION = "extraction"
    TIMELINE = "timeline"
    GRAPH = "graph"
    SUMMARY = "summary"


class EventType(Enum):
    """Type of audit event."""
    CHAIN_CREATED = "chain_created"
    CHAIN_UPDATED = "chain_updated"
    CHAIN_DELETED = "chain_deleted"
    LINK_ADDED = "link_added"
    LINK_REMOVED = "link_removed"
    LINK_VERIFIED = "link_verified"
    ARTIFACT_TRACKED = "artifact_tracked"
    AUDIT_GENERATED = "audit_generated"
    EXPORT_COMPLETED = "export_completed"


@dataclass
class EvidenceChain:
    """An evidence chain tracking artifact provenance."""
    id: str
    title: str
    description: str = ""
    status: ChainStatus = ChainStatus.DRAFT

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)

    # Ownership
    created_by: Optional[str] = None
    project_id: Optional[str] = None

    # Statistics
    link_count: int = 0
    artifact_count: int = 0

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)
    tags: List[str] = field(default_factory=list)

    # Verification
    verified: bool = False
    verified_by: Optional[str] = None
    verified_at: Optional[datetime] = None
    verification_notes: str = ""


@dataclass
class ProvenanceLink:
    """A link between two artifacts in a provenance chain."""
    id: str
    chain_id: str

    # Link endpoints
    source_artifact_id: str
    target_artifact_id: str

    # Link properties
    link_type: LinkType
    confidence: float = 1.0  # 0.0 to 1.0

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)

    # Verification
    verified: bool = False
    verified_by: Optional[str] = None
    verified_at: Optional[datetime] = None

    # Additional context
    metadata: Dict[str, Any] = field(default_factory=dict)
    notes: str = ""

    # Transformation details (if applicable)
    transformation_process: Optional[str] = None
    transformation_params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TrackedArtifact:
    """An artifact being tracked in the provenance system."""
    id: str  # Internal ID
    artifact_id: str  # External artifact ID
    artifact_type: ArtifactType
    shard_name: str  # Which shard created this

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)

    # Context
    project_id: Optional[str] = None

    # Metadata from source shard
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Lineage statistics
    upstream_count: int = 0  # Number of dependencies
    downstream_count: int = 0  # Number of dependents


@dataclass
class AuditRecord:
    """An audit log record."""
    id: str

    # Event details
    event_type: EventType
    event_source: str  # Shard or service that triggered event
    event_data: Dict[str, Any]

    # Timestamp
    timestamp: datetime = field(default_factory=datetime.utcnow)

    # Context
    chain_id: Optional[str] = None
    user_id: Optional[str] = None

    # Additional metadata
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LineageNode:
    """A node in a lineage graph."""
    id: str
    artifact_id: str
    artifact_type: ArtifactType
    shard_name: str
    label: str

    # Visual properties (for graph rendering)
    level: int = 0  # Depth in graph
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LineageEdge:
    """An edge in a lineage graph."""
    source: str  # Source node ID
    target: str  # Target node ID
    link_type: LinkType
    confidence: float

    # Visual properties
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LineageGraph:
    """A complete lineage graph for an artifact."""
    artifact_id: str
    direction: str  # upstream, downstream, both

    nodes: List[LineageNode] = field(default_factory=list)
    edges: List[LineageEdge] = field(default_factory=list)

    # Graph statistics
    total_nodes: int = 0
    total_edges: int = 0
    max_depth: int = 0

    # Metadata
    generated_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class VerificationResult:
    """Result of chain verification."""
    chain_id: str
    verified: bool

    # Issues found during verification
    issues: List[Dict[str, Any]] = field(default_factory=list)
    warnings: List[Dict[str, Any]] = field(default_factory=list)

    # Verification details
    checked_at: datetime = field(default_factory=datetime.utcnow)
    checked_by: Optional[str] = None

    # Statistics
    links_checked: int = 0
    links_verified: int = 0
    artifacts_checked: int = 0

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ChainExport:
    """Exported chain data."""
    chain: EvidenceChain
    links: List[ProvenanceLink]
    artifacts: List[TrackedArtifact]
    audit_trail: List[AuditRecord]

    # Export metadata
    exported_at: datetime = field(default_factory=datetime.utcnow)
    exported_by: Optional[str] = None
    export_format: str = "json"

    # Export options
    include_metadata: bool = True
    include_audit: bool = True
    include_verification: bool = True
